name: Maven Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
 user: hello-user

jobs:
  build-test:
    runs-on: ec2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: working dir
        run: echo "the user is $user "

     
          name: app-jar
          path: target/*.jar
