name: Maven Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
 user: hello-user

jobs:
  build-test:
    if: github.repository == 'bhuvan/maven-githubactions'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
